[profile.default]
build_info = true
extra_output = ['storageLayout']
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
solc_version = '0.8.20'
optimizer = true
optimizer_runs = 200
remappings = [
    'forge-std/=lib/forge-std/src/',
    '@openzeppelin/=node_modules/@openzeppelin/'
]